spring:
  cloud:
    aws:
      accessKey: AKIA3MNTDUSQBRH6SJMF
      secretKey: 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
      region: ap-south-1

  jpa:
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        id:
          new_generator_mappings: false
        jdbc:
          lob:
            ddl-non_contextual_creation: true # When you launch the application for the first time - switch "none" at "create"
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: create
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
#Security
security:
  user:
    name: api-prod
    password: pRd&$3yicr9bI_RUvOYEs
# Server configuration
server:
  port: 9002
  tomcat:
    accesslog:
      enabled: true
    basedir: tomcat

# Actuator Health Checks
management:
  endpoints:
    web.base-path: /effigo/payment/integration
    health.path: /health
    info.path: /info

#JWT configuration
secret:
  username: api-prod
  password: pRd&$3yicr9bI_RUvOYEs
  key: my-secret-key@123
  validityInDays: 2
tenants:
  datasources:
    kbl:
      jdbcUrl: ${DB_URL}
      driverClassName: org.postgresql.Driver
      schema:
      username: ${DB_USER}
      password: ${DB_PASSWORD}

    kbl-u:
      jdbcUrl: ${DB_URL}
      driverClassName: org.postgresql.Driver
      schema:
      username: ${DB_USER}
      password: ${DB_PASSWORD}

    default:
      jdbcUrl: ${DB_URL}
      driverClassName: org.postgresql.Driver
      schema: 
      username: ${DB_USER}
      password: ${DB_PASSWORD}

  security:
    admin:
      username: admin
      password: OlJ1Y3CEoDPRbGt2Jajbhw==
  accessKey: iHofE52hm3LsWNrPK1m_YX5IX2gcWrWjZ8El7baauJg

  exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
  logging:
    level:
      com:
        jcraft:
          jsch: WARN
excludebasicauthurls:
  - /effigo/payment/integration
  - /effigo/payment/integration/addPayment
  - /effigo/payment/integration/health
  - /effigo/payment/integration/info
  - /effigo/payment/integration/v1/**
  - /effigo/payment/integration/v1/**/**


auditServiceStatusUrl:
outbound:
  apiTimeout: 180000
inbound:
  poTimeout: 1200000

