spring:
  cloud:
    aws:
      accessKey: AKIA3MNTDUSQBRH6SJMF
      secretKey: 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
      region: ap-south-1

  jpa:
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        id:
          new_generator_mappings: false
        jdbc:
          lob:
            ddl-non_contextual_creation: true # When you launch the application for the first time - switch "none" at "create"
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: create
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
#Security
security:
  user:
    name: qa
    password: pwd@123
# Server configuration
server:
  port: 9002
  tomcat:
    accesslog:
      enabled: true
    basedir: tomcat

# Actuator Health Checks
management:
  endpoints:
    web.base-path: /effigo/payment/integration
    health.path: /health
    info.path: /info

#JWT configuration
secret:
  username: test
  password: test
  key: my-secret-key@123
  validityInDays: 2

tenants:
  datasources:
    varroc:
      jdbcUrl: jdbc:postgresql://shared-preprod.clxvybcdn8fq.ap-south-1.rds.amazonaws.com:5432/varroc_dev_integrations?currentSchema=upeg
      driverClassName: org.postgresql.Driver
      schema:
      username: upeg
      password: KjpIQ4CzJu4tLCYnz6cY0w==
    tatareality:
      jdbcUrl: jdbc:postgresql://shared-preprod.clxvybcdn8fq.ap-south-1.rds.amazonaws.com:5432/tata_integration?currentSchema=upeg
      driverClassName: org.postgresql.Driver
      schema:
      username: upeg
      password: KjpIQ4CzJu4tLCYnz6cY0w==
    ghcl:
      jdbcUrl: jdbc:postgresql://shared-preprod.clxvybcdn8fq.ap-south-1.rds.amazonaws.com:5432/ghcl_dev_integrations?currentSchema=upeg
      driverClassName: org.postgresql.Driver
      schema:
      username: upeg
      password: KjpIQ4CzJu4tLCYnz6cY0w==
    usha:
      jdbcUrl: jdbc:postgresql://devops.c2dkbebncahn.us-east-2.rds.amazonaws.com:5432/usha_prod31may23
      driverClassName: org.postgresql.Driver
      schema:
      username: upeg
      password: KjpIQ4CzJu4tLCYnz6cY0w==
    kbl:
      jdbcUrl: jdbc:postgresql://az-preprod4.postgres.database.azure.com:5432/kbl_demo
      driverClassName: org.postgresql.Driver
      schema:
      username: masters
      password: KjpIQ4CzJu4tLCYnz6cY0w==
    tataele:
      jdbcUrl: jdbc:postgresql://shared-preprod.clxvybcdn8fq.ap-south-1.rds.amazonaws.com/tata_electronics_dev
      driverClassName: org.postgresql.Driver
      schema:
      username: masters
      password: KjpIQ4CzJu4tLCYnz6cY0w==
    default:
      jdbcUrl: jdbc:postgresql://shared-preprod.clxvybcdn8fq.ap-south-1.rds.amazonaws.com:5432/ghcl_dev_integrations?currentSchema=upeg
      driverClassName: org.postgresql.Driver
      schema:
      username: upeg
      password: KjpIQ4CzJu4tLCYnz6cY0w==
  internallinks:


  externallinks:

    soap:
      username:
      password:
      accesskey:
      links:
        link1: http://localhost:9090/bob/ws/inbounddelivery
        link2: http://localhost:9090/bob/ws/grn

  security:
    tatareality:
      username: devuser12
      password: ff8080817c2178bf017c2178f52f0001
    csscorp:
      username: devuser34
      password: ff8080817c2178bf017c2178652f7311
    admin:
      username: admin
      password: OlJ1Y3CEoDPRbGt2Jajbhw==
  accessKey: iHofE52hm3LsWNrPK1m_YX5IX2gcWrWjZ8El7baauJg
  exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
  logging:
    level:
      com:
        jcraft:
          jsch: WARN
excludebasicauthurls:
  - /effigo/payment/integration
  - /effigo/payment/integration/addPayment
  - /effigo/payment/integration/health
  - /effigo/payment/integration/info
  - /effigo/payment/integration/v1/**
  - /effigo/payment/integration/v1/**/**


queue: api_transactions_local
auditServiceStatusUrl: http://localhost:9000/effigo/api/external/audit/v1/{txnId}/status
outbound:
  apiTimeout: 180000
inbound:
  poTimeout: 1200000

