version: '3'

services:
  shared-web-uat:
    container_name: shared-web-uat
    image: registry.gitlab.com/effigonew/shared/utility/shared-web:uat
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '6006:3000'
    env_file:
      - .env.uat

    environment: 
     - REACT_APP_IPC_EFFIGO = https://shared-payment-integration-uat.effigo.in/
     - REACT_APP_PO_EFFIGO=https://shared-po-integration-uat.effigo.in/
     - REACT_APP_PDF_EFFIGO=https://varrocuat.effigo.in/
     - REACT_APP_EFFIGO_USERNAME_VARROC = 'api-uat'
     - REACT_APP_EFFIGO_PASSWORD_VARROC = 'g3AHjk8FS4YqPAYX'
     - REACT_APP_EFFIGO_USERNAME_TATA = 'api-uat'
     - REACT_APP_EFFIGO_PASSWORD_TATA = 'g3AHjk8FS4YqPAYX'
     - REACT_APP_EFFIGO_MATERIAL = https://grn-api-uat.effigo.in/