version: '3'

services:
  shared-web-uat:
    container_name: shared-web-uat2
    image: registry.gitlab.com/effigonew/shared/utility/shared-web:uat2
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '6006:3000'
    env_file:
      - .env.uat2
