version: '3'

services:
  shared-web-dev:
    container_name: shared-web-dev
    image: registry.gitlab.com/effigonew/shared/utility/shared-web:dev
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '6002:3000'
    env_file:
      - .env.kbl.dev
