version: '3'

services:
  shared-web-staging:
    container_name: shared-web-staging
    image: registry.gitlab.com/effigonew/shared/utility/shared-web:staging
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '6003:3000'
    env_file:
      - .env.staging
