version: '3'

services:
  shared-web-uat:
    container_name: shared-web-uat
    image: registry.gitlab.com/effigonew/shared/utility/shared-web:uat
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '6006:3000'
    env_file:
      - .env.kbl.uat
